const timeFrames = {
  timeFrame4h: '4h',
  //timeFrame4h: '5m', // для тестов
  timeFrame2h: '2h',
  timeFrame15m: '15m',
  timeFrame5m: '5m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice4h41: `Test_4.1 на ${timeFrames.timeFrame4h}`,
  notice5m41: `Test_4.1 на ${timeFrames.timeFrame5m}`,
}

//const symbols4h41 = ['UNFIUSDT', 'XRPUSDT', 'BLZUSDT']

const symbols4h41 = [
  '1INCHUSDT',
  '1000SHIBUSDT',
  'ALICEUSDT',
  'ADAUSDT',
  'ATOMUSDT',
  'AVAXUSDT',
  'AXSUSDT',
  'APEUSDT',
  'ALGOUSDT',
  'ANKRUSDT',
  'AAVEUSDT',
  'ARUSDT',
  'AUDIOUSDT',
  'AAVEUSDT',
  'BAKEUSDT',
  'BNXUSDT',
  'BLZUSDT',
  'CHZUSDT',
  'CHRUSDT',
  'CRVUSDT',
  'COMPUSDT',
  //'CVXUSDT',
  'CTKUSDT',
  'COTIUSDT',
  'C98USDT',
  'DASHUSDT',
  'DYDXUSDT',
  'DOTUSDT',
  'DOGEUSDT',
  'DGBUSDT',
  'DUSKUSDT',
  'ENJUSDT',
  'ETCUSDT',
  'EOSUSDT',
  'JASMYUSDT',
  'LINKUSDT',
  'FILUSDT',
  'FLMUSDT',
  'FTMUSDT',
  'ICPUSDT',
  'HNTUSDT',
  'KAVAUSDT',
  'KNCUSDT',
  'KSMUSDT',
  'GALUSDT',
  'GALAUSDT',
  'GTCUSDT',
  'NEARUSDT',
  'NEOUSDT',
  'NKNUSDT',
  'MATICUSDT',
  'MANAUSDT',
  'MASKUSDT',
  'THETAUSDT',
  'TRBUSDT',
  'TRXUSDT',
  'OPUSDT',
  'OMGUSDT',
  'OCEANUSDT',
  'SANDUSDT',
  'SUSHIUSDT',
  'SOLUSDT',
  'SNXUSDT',
  'STMXUSDT',
  'STORJUSDT',
  'REEFUSDT',
  'RUNEUSDT',
  'RLCUSDT',
  'RVNUSDT',
  'RSRUSDT',
  'ROSEUSDT',
  'ZRXUSDT',
  'ZECUSDT',
  'VETUSDT',
  'XEMUSDT',
  'XRPUSDT',
  'XLMUSDT',
  'XTZUSDT',
  'YFIUSDT',
  'UNIUSDT',
  'UNFIUSDT',
  'WAVESUSDT',
]

module.exports = {
  symbols4h41,
  timeFrames,
  nameStrategy,
}
