const timeFrames = {
  timeFrame2h: '2h',
  timeFrame15m: '15m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice2h382: `Стратегия №3.8.2: Без теневая на ${timeFrames.timeFrame2h}`,
  notice15m382: `Стратегия №3.8.2: Без теневая на ${timeFrames.timeFrame15m}`,
}

// 06.09.2022 для alex38Notice2h (перенос TP SL: сразу после закрытия свечи, на которой открылись)
const symbols2h38 = [
  'UNFIUSDT',
  'BLZUSDT',
  'ARPAUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'APEUSDT',
  'ATOMUSDT',
  'ALPHAUSDT',
  'API3USDT',
  'BANDUSDT',
  'CTKUSDT',
  'C98USDT',
  'COMPUSDT',
  'DGBUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'GALUSDT',
  'STORJUSDT',
  'SANDUSDT',
  'DASHUSDT',
  'HOTUSDT',
  'LINAUSDT',
  'MANAUSDT',
  'RSRUSDT',
  'GMTUSDT',
  'XRPUSDT',
]

const symbols15m38 = [
  //'1000SHIBUSDT',
  //'1INCHUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'ALGOUSDT',
  //'ALPHAUSDT',
  'ANCUSDT',
  'APEUSDT',
  'API3USDT',
  'ARPAUSDT',
  //'ATOMUSDT',
  'AVAXUSDT',
  'BANDUSDT',
  'BELUSDT',
  'BLZUSDT',
  'BNBUSDT',
  //'C98USDT',
  //'CELOUSDT',
  'COMPUSDT',
  //'CRVUSDT',
  //'CTKUSDT',
  'DARUSDT',
  //'DASHUSDT',
  'DGBUSDT',
  //'DOTUSDT',
  //'EGLDUSDT',
  //'ENJUSDT',
  //'ENSUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'ETHUSDT',
  'FILUSDT',
  //'FTMUSDT',
  'GALUSDT',
  'GMTUSDT',
  //'HBARUSDT',
  //'HNTUSDT',
  'HOTUSDT',
  //'KAVAUSDT',
  //'LINAUSDT',
  //'LINKUSDT',
  //'MANAUSDT',
  'PEOPLEUSDT',
  'RSRUSDT',
  //'RVNUSDT',
  'SANDUSDT',
  'SNXUSDT',
  //'SOLUSDT',
  'STORJUSDT',
  'THETAUSDT',
  //'TRBUSDT',
  //'TRXUSDT',
  'UNFIUSDT',
  'UNIUSDT',
  //'VETUSDT',
  //'WAVESUSDT',
  //'XMRUSDT',
  'XRPUSDT',
  //'XTZUSDT',
]

module.exports = {
  symbols2h38,
  symbols15m38,
  timeFrames,
  nameStrategy,
}
