const timeFrames = {
  timeFrame2h: '2h',
  timeFrame15m: '15m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice2h384: `Стратегия №3.8.4: Без теневая на ${timeFrames.timeFrame2h}`,
  notice15m384: `Стратегия №3.8.4: Без теневая на ${timeFrames.timeFrame15m}`,
}

const symbols2h384 = [
  'UNFIUSDT',
  'AVAXUSDT',
  'ARPAUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'APEUSDT',
  'ATOMUSDT',
  //'ALPHAUSDT',
  'API3USDT',
  //'BELUSDT',
  'BNBUSDT',
  'BANDUSDT',
  'CELOUSDT',
  'CTKUSDT',
  'C98USDT',
  'COMPUSDT',
  'PEOPLEUSDT',
  'DGBUSDT',
  'EGLDUSDT',
  'EOSUSDT',
  'ENJUSDT',
  'ETCUSDT',
  'ETHUSDT',
  '1INCHUSDT',
  'GALUSDT',
  'STORJUSDT',
  'SANDUSDT',
  'DASHUSDT',
  'DOTUSDT',
  'DARUSDT',
  'HOTUSDT',
  'HNTUSDT',
  'HBARUSDT',
  'LINAUSDT',
  'LINKUSDT',
  'MANAUSDT',
  'RVNUSDT',
  'RSRUSDT',
  'TRBUSDT',
  'TRXUSDT',
  'KAVAUSDT',
  'THETAUSDT',
  'GMTUSDT',
  'XRPUSDT',
  'XMRUSDT',
  'WAVESUSDT',
]

const symbols15m384 = [
  'UNFIUSDT',
  'AVAXUSDT',
  'ARPAUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'APEUSDT',
  'ATOMUSDT',
  'ALPHAUSDT',
  'API3USDT',
  'BELUSDT',
  'BNBUSDT',
  'BANDUSDT',
  'CELOUSDT',
  'CTKUSDT',
  'C98USDT',
  'COMPUSDT',
  'PEOPLEUSDT',
  'DGBUSDT',
  'EGLDUSDT',
  'EOSUSDT',
  'ENJUSDT',
  'ETCUSDT',
  'ETHUSDT',
  '1INCHUSDT',
  'GALUSDT',
  'STORJUSDT',
  'SANDUSDT',
  'DASHUSDT',
  'DOTUSDT',
  'DARUSDT',
  'HOTUSDT',
  'HNTUSDT',
  'HBARUSDT',
  'LINAUSDT',
  'LINKUSDT',
  'MANAUSDT',
  'RVNUSDT',
  'RSRUSDT',
  'TRBUSDT',
  'TRXUSDT',
  'KAVAUSDT',
  'THETAUSDT',
  'GMTUSDT',
  'XRPUSDT',
  'XMRUSDT',
  'WAVESUSDT',
]

module.exports = {
  symbols2h384,
  symbols15m384,
  timeFrames,
  nameStrategy,
}
