const timeFrames = {
  timeFrame2h: '2h',
  //timeFrame15m: '15m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice2h3825: `Стратегия №3.8.2.5: Без теневая на ${timeFrames.timeFrame2h}`,
  // notice15m382: `Стратегия №3.8.2.5: Без теневая на ${timeFrames.timeFrame15m}`,
}

// 11.09.2022
/*
const symbols2h3825 = [
  '1000SHIBUSDT',
  '1INCHUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'ALGOUSDT',
  'ALPHAUSDT',
  'ANCUSDT',
  'APEUSDT',
  'API3USDT',
  'ARPAUSDT',
  'ATOMUSDT',
  'AVAXUSDT',
  'BANDUSDT',
  'BELUSDT',
  'BLZUSDT',
  'BNBUSDT',
  'C98USDT',
  'CELOUSDT',
  'COMPUSDT',
  'CRVUSDT',
  'CTKUSDT',
  'DARUSDT',
  'DASHUSDT',
  'DGBUSDT',
  'DOTUSDT',
  'EGLDUSDT',
  'ENJUSDT',
  'ENSUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'ETHUSDT',
  'FILUSDT',
  'FTMUSDT',
  'GALUSDT',
  'GMTUSDT',
  'HBARUSDT',
  'HNTUSDT',
  'HOTUSDT',
  'KAVAUSDT',
  'LINAUSDT',
  'LINKUSDT',
  'MANAUSDT',
  'PEOPLEUSDT',
  'RSRUSDT',
  'RVNUSDT',
  'SANDUSDT',
  'SNXUSDT',
  'SOLUSDT',
  'STORJUSDT',
  'THETAUSDT',
  'TRXUSDT',
  'UNFIUSDT',
  'UNIUSDT',
  'VETUSDT',
  'WAVESUSDT',
  'XMRUSDT',
  'XRPUSDT',
]
*/

// 12.09.2022
/*
const symbols2h3825 = [
  '1000SHIBUSDT',
  '1INCHUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'ALGOUSDT',
  //'ALPHAUSDT',
  'ANCUSDT',
  'APEUSDT',
  'API3USDT',
  'ARPAUSDT',
  'ATOMUSDT',
  //'AVAXUSDT',
  //'BANDUSDT',
  'BLZUSDT',
  'C98USDT',
  'CELOUSDT',
  //'COMPUSDT',
  //'CRVUSDT',
  'CTKUSDT',
  'DARUSDT',
  'DASHUSDT',
  'DGBUSDT',
  //'DOTUSDT',
  //'EGLDUSDT',
  //'ENJUSDT',
  'ENSUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'FILUSDT',
  'GALUSDT',
  //'GMTUSDT',
  'HNTUSDT',
  'HOTUSDT',
  'KAVAUSDT',
  'LINAUSDT',
  //'LINKUSDT',
  'MANAUSDT',
  'PEOPLEUSDT',
  //'RSRUSDT',
  //'RVNUSDT',
  'SANDUSDT',
  'SNXUSDT',
  //'STORJUSDT',
  'UNFIUSDT',
  'XRPUSDT',
]
*/

// 13.09.2022
const symbols2h3825 = [
  //'1000SHIBUSDT',
  '1INCHUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'ALGOUSDT',
  'APEUSDT',
  'API3USDT',
  'ARPAUSDT',
  'ATOMUSDT',
  'BLZUSDT',
  'C98USDT',
  'CELOUSDT',
  'CTKUSDT',
  //'DARUSDT',
  'DASHUSDT',
  'DGBUSDT',
  'ENSUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'FILUSDT',
  'GALUSDT',
  'HNTUSDT',
  'HOTUSDT',
  //'KAVAUSDT',
  'LINAUSDT',
  'MANAUSDT',
  //'PEOPLEUSDT',
  'SANDUSDT',
  'SNXUSDT',
  'UNFIUSDT',
  'XRPUSDT',
  'FLOWUSDT',
]

module.exports = {
  symbols2h3825,
  timeFrames,
  nameStrategy,
}
