const timeFrames = {
  timeFrame2h: '2h',
  timeFrame15m: '15m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice2h382: `3.8.2.6: Без теневая на ${timeFrames.timeFrame2h}`,
  //notice15m382: `Стратегия №3.8.2: Без теневая на ${timeFrames.timeFrame15m}`,
}

// 02.10.2022 разделил 100 монет по 50
const symbols2h38Part1 = [
  'BTCUSDT',
  'ATAUSDT',
  'ETHUSDT',
  'BNBUSDT',
  '1INCHUSDT',
  '1000SHIBUSDT',
  'ALICEUSDT',
  'ADAUSDT',
  'ATOMUSDT',
  'AVAXUSDT',
  'AXSUSDT',
  'APEUSDT',
  'ALGOUSDT',
  'ANKRUSDT',
  'AAVEUSDT',
  'ARUSDT',
  'AUDIOUSDT',
  'BAKEUSDT',
  'BALUSDT',
  'BELUSDT',
  'BNXUSDT',
  'BLZUSDT',
  'CHZUSDT',
  'CHRUSDT',
  'CRVUSDT',
  'COMPUSDT',
  'CVXUSDT',
  'CTSIUSDT',
  'CTKUSDT',
  'COTIUSDT',
  'C98USDT',
  'DASHUSDT',
  'DYDXUSDT',
  'DOTUSDT',
  'DOGEUSDT',
  'DGBUSDT',
  'DUSKUSDT',
  'ENJUSDT',
  'ETCUSDT',
  'EOSUSDT',
  'JASMYUSDT',
  'LRCUSDT',
  'LINKUSDT',
  'FILUSDT',
  'FLMUSDT',
  'FTMUSDT',
  'FTTUSDT',
  'FLOWUSDT',
  'ICPUSDT',
  'IOTAUSDT',
  'IOSTUSDT',
  'ICXUSDT',
  'LINAUSDT',
]

const symbols2h38Part2 = [
  'QTUMUSDT',
  'HNTUSDT',
  'HBARUSDT',
  'KAVAUSDT',
  'KNCUSDT',
  'KSMUSDT',
  'KLAYUSDT',
  'GALUSDT',
  'GALAUSDT',
  'GTCUSDT',
  'GMTUSDT',
  'NEARUSDT',
  'NEOUSDT',
  'NKNUSDT',
  'MATICUSDT',
  'MANAUSDT',
  'MASKUSDT',
  'MTLUSDT',
  'THETAUSDT',
  'TRBUSDT',
  'TRXUSDT',
  'OGNUSDT',
  'OPUSDT',
  'OMGUSDT',
  'OCEANUSDT',
  'SANDUSDT',
  'SRMUSDT',
  'SKLUSDT',
  'STGUSDT',
  'SUSHIUSDT',
  'SOLUSDT',
  'SNXUSDT',
  'STMXUSDT',
  'STORJUSDT',
  'PEOPLEUSDT',
  'REEFUSDT',
  'RUNEUSDT',
  'RLCUSDT',
  'RVNUSDT',
  'RSRUSDT',
  'ROSEUSDT',
  'ZRXUSDT',
  'ZECUSDT',
  'VETUSDT',
  'XEMUSDT',
  'XRPUSDT',
  'XLMUSDT',
  'XTZUSDT',
  'YFIUSDT',
  'UNIUSDT',
  'UNFIUSDT',
  'WAVESUSDT',
  'FOOTBALLUSDT',
]

module.exports = {
  symbols2h38Part1,
  symbols2h38Part2,
  timeFrames,
  nameStrategy,
}
