const timeFrames = {
  timeFrame2h: '2h',
  timeFrame15m: '15m',
  timeFrame1m: '1m',
}

const nameStrategy = {
  notice2h3824: `Стратегия №3.8.2.4: Без теневая на ${timeFrames.timeFrame2h}`,
  //notice15m3824: `Стратегия №3.8.2.4: Без теневая на ${timeFrames.timeFrame15m}`,
}

// 10.09.2022
const symbols2h3824 = [
  '1000SHIBUSDT',
  '1INCHUSDT',
  'AAVEUSDT',
  'ADAUSDT',
  'ALGOUSDT',
  'ALPHAUSDT',
  'ANCUSDT',
  'APEUSDT',
  'API3USDT',
  'ARPAUSDT',
  'ATOMUSDT',
  'AVAXUSDT',
  'BANDUSDT',
  'BELUSDT',
  'BLZUSDT',
  'BNBUSDT',
  'C98USDT',
  'CELOUSDT',
  'COMPUSDT',
  'CRVUSDT',
  'CTKUSDT',
  'DARUSDT',
  'DASHUSDT',
  'DGBUSDT',
  'DOTUSDT',
  'EGLDUSDT',
  'ENJUSDT',
  'ENSUSDT',
  'EOSUSDT',
  'ETCUSDT',
  'ETHUSDT',
  'FILUSDT',
  'FTMUSDT',
  'GALUSDT',
  'GMTUSDT',
  'HBARUSDT',
  'HNTUSDT',
  'HOTUSDT',
  'KAVAUSDT',
  'LINAUSDT',
  'LINKUSDT',
  'MANAUSDT',
  'PEOPLEUSDT',
  'RSRUSDT',
  'RVNUSDT',
  'SANDUSDT',
  'SNXUSDT',
  'SOLUSDT',
  'STORJUSDT',
  'THETAUSDT',
  'TRBUSDT',
  'TRXUSDT',
  'UNFIUSDT',
  'UNIUSDT',
  'VETUSDT',
  'WAVESUSDT',
  'XMRUSDT',
  'XRPUSDT',
  'XTZUSDT',
]

module.exports = {
  symbols2h3824,
  timeFrames,
  nameStrategy,
}
